In [41]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [42]:
df = pd.read_csv(r"C:\Users\camil\Documents\Estudio\Seminario\Bases de datos\IPM_2018_2024_CLEAN_CARIBE.csv",sep = ';')

In [43]:
df.shape

(135835, 28)

In [44]:
df.head()

,cuartos_dormir,tipo_sanitario,fuente_agua,fex_c,region,departamento,personas,paredes,pisos,alcantarillado,...,rezago_escolar,alfabetismo,logro_educativo,hacinamiento,ipm,pobre,fexp,region_nombre,departamento_nombre,año
0,2,1,1,"384,3281693",1,8,2,0,0,0,...,0,0,0,0,"0,1",0,"768,6563387",Caribe,ATLANTICO,2018
1,2,1,1,"297,1724562",1,8,3,0,0,0,...,0,0,0,0,"0,2",0,"891,5173685",Caribe,ATLANTICO,2018
2,2,1,1,"274,6401305",1,8,3,0,0,0,...,0,0,1,0,"0,2",0,"823,9203915",Caribe,ATLANTICO,2018
3,1,1,1,"397,4006806",1,8,2,0,0,0,...,0,0,1,0,"0,3",0,"794,8013612",Caribe,ATLANTICO,2018
4,1,6,1,"19,35421293",1,8,1,0,1,1,...,0,0,1,0,"0,18",0,"19,35421293",Caribe,ATLANTICO,2018

In [45]:
df.columns

Index(['cuartos_dormir', 'tipo_sanitario', 'fuente_agua', 'fex_c', 'region',
       'departamento', 'personas', 'paredes', 'pisos', 'alcantarillado',
       'acueducto', 'empleo_formal', 'desempleo_larga_duracion',
       'barreras_acceso_salud', 'aseguramiento_salud', 'trabajo_infantil',
       'atencion_integral', 'inasistencia_escolar', 'rezago_escolar',
       'alfabetismo', 'logro_educativo', 'hacinamiento', 'ipm', 'pobre',
       'fexp', 'region_nombre', 'departamento_nombre', 'año'],
      dtype='object')

In [46]:
df.dtypes

cuartos_dormir               int64
tipo_sanitario               int64
fuente_agua                  int64
fex_c                       object
region                       int64
departamento                 int64
personas                     int64
paredes                      int64
pisos                        int64
alcantarillado               int64
acueducto                    int64
empleo_formal                int64
desempleo_larga_duracion     int64
barreras_acceso_salud        int64
aseguramiento_salud          int64
trabajo_infantil             int64
atencion_integral            int64
inasistencia_escolar         int64
rezago_escolar               int64
alfabetismo                  int64
logro_educativo              int64
hacinamiento                 int64
ipm                         object
pobre                        int64
fexp                        object
region_nombre               object
departamento_nombre         object
año                          int64
dtype: object

In [47]:
df.describe()

,cuartos_dormir,tipo_sanitario,fuente_agua,region,departamento,personas,paredes,pisos,alcantarillado,acueducto,...,aseguramiento_salud,trabajo_infantil,atencion_integral,inasistencia_escolar,rezago_escolar,alfabetismo,logro_educativo,hacinamiento,pobre,año
count,135835.000000,135835.000000,135835.000000,135835.0,135835.000000,135835.000000,135835.000000,135835.000000,135835.000000,135835.000000,...,135835.000000,135835.000000,135835.000000,135835.000000,135835.000000,135835.000000,135835.000000,135835.000000,135835.000000,135835.000000
mean,1.755026,2.239923,2.554835,1.0,31.565031,3.343387,0.036809,0.225030,0.267935,0.225376,...,0.092848,0.017345,0.090882,0.083020,0.307299,0.204174,0.560084,0.138013,0.277506,2020.912416
std,0.770890,1.719451,2.434362,0.0,20.795113,1.767933,0.188294,0.417604,0.442885,0.417831,...,0.290220,0.130552,0.287443,0.275913,0.461376,0.403098,0.496379,0.344915,0.447770,1.998827
min,1.000000,1.000000,1.000000,1.0,8.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2018.000000
25%,1.000000,1.000000,1.000000,1.0,13.000000,2.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2019.000000
50%,2.000000,2.000000,1.000000,1.0,23.000000,3.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,2021.000000
75%,2.000000,2.000000,4.000000,1.0,47.000000,4.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,2023.000000
max,9.000000,6.000000,10.000000,1.0,70.000000,22.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2024.000000

In [48]:
df.describe(include= 'object')

              fex_c     ipm         fexp region_nombre departamento_nombre
count        135835  135835       135835        135835              135835
unique       101622      75       103121             1                   7
top     19,35421293     0,1  19,35421293        Caribe             BOLIVAR
freq            104   16534          104        135835               21511

- Para el IPM observamos un total de 75 clasificasiones diferentes
- Se divide en 7 departamentos en los que se incluye: 'ATLANTICO' 'CORDOBA' 'MAGDALENA' 'SUCRE' 'BOLIVAR' 'LA GUAJIRA' 'CESAR'. Cabe aclarar que 'San Andrés y Providencia no se encuentra en el dataset del DANE como región caribe.
- El departamento con más representación dentro del dataset es el departamento de bolivar

AttributeError: 'DataFrame' object has no attribute 'REGION_NOMBRE'

In [52]:
print(df.departamento_nombre.unique())

['ATLANTICO' 'CORDOBA' 'MAGDALENA' 'SUCRE' 'BOLIVAR' 'LA GUAJIRA' 'CESAR']